
GET  http://localhost:5230
###

//Query paramiter==?search="apple"
//GET  http://localhost:5230/api/categories?searchValue=Electorinics
GET  http://localhost:5230/api/categories
###

POST http://localhost:5230/api/categories
Content-Type: application/json

{ 
  "name" :"Redmi Node 12pro",
  "description": "Electronics is redmi of devices ."
}
###

PUT http://localhost:5230/api/categories/29861181-5895-4d53-b090-3200d52d18d1
Content-Type: application/json

{
  "name":"Laptop",
  "description":"How do I type and print a letter on my laptop?" 
}
###

DELETE http://localhost:5230/api/categories/8a55f0f0-7cfa-4f63-981c-0bd207a99fa6
