
GET  http://localhost:5230
###

GET  http://localhost:5230/api/categories
###

POST http://localhost:5230/api/categories
###

PUT http://localhost:5230/api/categories
###

DELETE http://localhost:5230/api/categories