
GET  http://localhost:5230
###

//Query paramiter==?search="apple"
//GET  http://localhost:5230/api/categories?searchValue=Electorinics
GET  http://localhost:5230/api/categories
###

POST http://localhost:5230/api/categories
Content-Type: application/json

{
   "name":"Redmi 13Pro",
   "description": "My Redmi Phone."
}
###

PUT http://localhost:5230/api/categories/043da262-52c6-4060-b4c7-7269c7f5b79c
Content-Type: application/json


{
  "name": "",
  "description":"" 
}
###

DELETE http://localhost:5230/api/categories
